package com.example.model;

public class MCode extends MCodeKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_code.type_name
	 * @mbg.generated
	 */
	private String typeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_code.type
	 * @mbg.generated
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_code.value
	 * @mbg.generated
	 */
	private String value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_code.label
	 * @mbg.generated
	 */
	private String label;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_code.type_name
	 * @return  the value of m_code.type_name
	 * @mbg.generated
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_code.type_name
	 * @param typeName  the value for m_code.type_name
	 * @mbg.generated
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName == null ? null : typeName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_code.type
	 * @return  the value of m_code.type
	 * @mbg.generated
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_code.type
	 * @param type  the value for m_code.type
	 * @mbg.generated
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_code.value
	 * @return  the value of m_code.value
	 * @mbg.generated
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_code.value
	 * @param value  the value for m_code.value
	 * @mbg.generated
	 */
	public void setValue(String value) {
		this.value = value == null ? null : value.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_code.label
	 * @return  the value of m_code.label
	 * @mbg.generated
	 */
	public String getLabel() {
		return label;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_code.label
	 * @param label  the value for m_code.label
	 * @mbg.generated
	 */
	public void setLabel(String label) {
		this.label = label == null ? null : label.trim();
	}
}