package com.example.model;

public class MRoleKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_role.role_id
	 * @mbg.generated
	 */
	private String roleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_role.role_id
	 * @return  the value of m_role.role_id
	 * @mbg.generated
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_role.role_id
	 * @param roleId  the value for m_role.role_id
	 * @mbg.generated
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId == null ? null : roleId.trim();
	}
}