package com.example.model;

import java.util.ArrayList;
import java.util.List;

public class MTeamExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table m_team
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table m_team
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table m_team
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_team
	 * @mbg.generated
	 */
	public MTeamExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_team
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_team
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_team
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_team
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_team
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_team
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_team
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_team
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_team
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_team
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table m_team
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andTeamIdIsNull() {
			addCriterion("team_id is null");
			return (Criteria) this;
		}

		public Criteria andTeamIdIsNotNull() {
			addCriterion("team_id is not null");
			return (Criteria) this;
		}

		public Criteria andTeamIdEqualTo(Integer value) {
			addCriterion("team_id =", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdNotEqualTo(Integer value) {
			addCriterion("team_id <>", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdGreaterThan(Integer value) {
			addCriterion("team_id >", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("team_id >=", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdLessThan(Integer value) {
			addCriterion("team_id <", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdLessThanOrEqualTo(Integer value) {
			addCriterion("team_id <=", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdIn(List<Integer> values) {
			addCriterion("team_id in", values, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdNotIn(List<Integer> values) {
			addCriterion("team_id not in", values, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdBetween(Integer value1, Integer value2) {
			addCriterion("team_id between", value1, value2, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdNotBetween(Integer value1, Integer value2) {
			addCriterion("team_id not between", value1, value2, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamNameIsNull() {
			addCriterion("team_name is null");
			return (Criteria) this;
		}

		public Criteria andTeamNameIsNotNull() {
			addCriterion("team_name is not null");
			return (Criteria) this;
		}

		public Criteria andTeamNameEqualTo(String value) {
			addCriterion("team_name =", value, "teamName");
			return (Criteria) this;
		}

		public Criteria andTeamNameNotEqualTo(String value) {
			addCriterion("team_name <>", value, "teamName");
			return (Criteria) this;
		}

		public Criteria andTeamNameGreaterThan(String value) {
			addCriterion("team_name >", value, "teamName");
			return (Criteria) this;
		}

		public Criteria andTeamNameGreaterThanOrEqualTo(String value) {
			addCriterion("team_name >=", value, "teamName");
			return (Criteria) this;
		}

		public Criteria andTeamNameLessThan(String value) {
			addCriterion("team_name <", value, "teamName");
			return (Criteria) this;
		}

		public Criteria andTeamNameLessThanOrEqualTo(String value) {
			addCriterion("team_name <=", value, "teamName");
			return (Criteria) this;
		}

		public Criteria andTeamNameLike(String value) {
			addCriterion("team_name like", value, "teamName");
			return (Criteria) this;
		}

		public Criteria andTeamNameNotLike(String value) {
			addCriterion("team_name not like", value, "teamName");
			return (Criteria) this;
		}

		public Criteria andTeamNameIn(List<String> values) {
			addCriterion("team_name in", values, "teamName");
			return (Criteria) this;
		}

		public Criteria andTeamNameNotIn(List<String> values) {
			addCriterion("team_name not in", values, "teamName");
			return (Criteria) this;
		}

		public Criteria andTeamNameBetween(String value1, String value2) {
			addCriterion("team_name between", value1, value2, "teamName");
			return (Criteria) this;
		}

		public Criteria andTeamNameNotBetween(String value1, String value2) {
			addCriterion("team_name not between", value1, value2, "teamName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table m_team
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_team
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}