package com.example.model;

public class MTeamKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_team.team_id
	 * @mbg.generated
	 */
	private Integer teamId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_team.team_id
	 * @return  the value of m_team.team_id
	 * @mbg.generated
	 */
	public Integer getTeamId() {
		return teamId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_team.team_id
	 * @param teamId  the value for m_team.team_id
	 * @mbg.generated
	 */
	public void setTeamId(Integer teamId) {
		this.teamId = teamId;
	}
}