package com.example.model;

public class MUser extends MUserKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_user.login_id
	 * @mbg.generated
	 */
	private String loginId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_user.password
	 * @mbg.generated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_user.user_name
	 * @mbg.generated
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_user.delete_flag
	 * @mbg.generated
	 */
	private String deleteFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_user.role_id
	 * @mbg.generated
	 */
	private String roleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_user.login_id
	 * @return  the value of m_user.login_id
	 * @mbg.generated
	 */
	public String getLoginId() {
		return loginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_user.login_id
	 * @param loginId  the value for m_user.login_id
	 * @mbg.generated
	 */
	public void setLoginId(String loginId) {
		this.loginId = loginId == null ? null : loginId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_user.password
	 * @return  the value of m_user.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_user.password
	 * @param password  the value for m_user.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_user.user_name
	 * @return  the value of m_user.user_name
	 * @mbg.generated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_user.user_name
	 * @param userName  the value for m_user.user_name
	 * @mbg.generated
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_user.delete_flag
	 * @return  the value of m_user.delete_flag
	 * @mbg.generated
	 */
	public String getDeleteFlag() {
		return deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_user.delete_flag
	 * @param deleteFlag  the value for m_user.delete_flag
	 * @mbg.generated
	 */
	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_user.role_id
	 * @return  the value of m_user.role_id
	 * @mbg.generated
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_user.role_id
	 * @param roleId  the value for m_user.role_id
	 * @mbg.generated
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId == null ? null : roleId.trim();
	}

}