package com.example.model;

import java.util.Date;

public class TUserDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_detail.user_id
	 * @mbg.generated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_detail.start_of_work_time
	 * @mbg.generated
	 */
	private Date startOfWorkTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_detail.end_of_work_time
	 * @mbg.generated
	 */
	private Date endOfWorkTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_detail.team_id
	 * @mbg.generated
	 */
	private Integer teamId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_detail.delete_flag
	 * @mbg.generated
	 */
	private String deleteFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_detail.user_id
	 * @return  the value of t_user_detail.user_id
	 * @mbg.generated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_detail.user_id
	 * @param userId  the value for t_user_detail.user_id
	 * @mbg.generated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_detail.start_of_work_time
	 * @return  the value of t_user_detail.start_of_work_time
	 * @mbg.generated
	 */
	public Date getStartOfWorkTime() {
		return startOfWorkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_detail.start_of_work_time
	 * @param startOfWorkTime  the value for t_user_detail.start_of_work_time
	 * @mbg.generated
	 */
	public void setStartOfWorkTime(Date startOfWorkTime) {
		this.startOfWorkTime = startOfWorkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_detail.end_of_work_time
	 * @return  the value of t_user_detail.end_of_work_time
	 * @mbg.generated
	 */
	public Date getEndOfWorkTime() {
		return endOfWorkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_detail.end_of_work_time
	 * @param endOfWorkTime  the value for t_user_detail.end_of_work_time
	 * @mbg.generated
	 */
	public void setEndOfWorkTime(Date endOfWorkTime) {
		this.endOfWorkTime = endOfWorkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_detail.team_id
	 * @return  the value of t_user_detail.team_id
	 * @mbg.generated
	 */
	public Integer getTeamId() {
		return teamId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_detail.team_id
	 * @param teamId  the value for t_user_detail.team_id
	 * @mbg.generated
	 */
	public void setTeamId(Integer teamId) {
		this.teamId = teamId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_detail.delete_flag
	 * @return  the value of t_user_detail.delete_flag
	 * @mbg.generated
	 */
	public String getDeleteFlag() {
		return deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_detail.delete_flag
	 * @param deleteFlag  the value for t_user_detail.delete_flag
	 * @mbg.generated
	 */
	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
	}
}