package com.example.model;

import java.util.Date;

public class TUserDetail extends TUserDetailKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_detail.start_of_work_time
	 * @mbg.generated
	 */
	private String startOfWorkTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_detail.end_of_work_time
	 * @mbg.generated
	 */
	private String endOfWorkTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_detail.team_id
	 * @mbg.generated
	 */
	private Integer teamId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_detail.delete_flag
	 * @mbg.generated
	 */
	private String deleteFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_detail.start_of_work_time
	 * @return  the value of t_user_detail.start_of_work_time
	 * @mbg.generated
	 */
	public String getStartOfWorkTime() {
		return startOfWorkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_detail.start_of_work_time
	 * @param startOfWorkTime  the value for t_user_detail.start_of_work_time
	 * @mbg.generated
	 */
	public void setStartOfWorkTime(String startOfWorkTime) {
		this.startOfWorkTime = startOfWorkTime == null ? null : startOfWorkTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_detail.end_of_work_time
	 * @return  the value of t_user_detail.end_of_work_time
	 * @mbg.generated
	 */
	public String getEndOfWorkTime() {
		return endOfWorkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_detail.end_of_work_time
	 * @param endOfWorkTime  the value for t_user_detail.end_of_work_time
	 * @mbg.generated
	 */
	public void setEndOfWorkTime(String endOfWorkTime) {
		this.endOfWorkTime = endOfWorkTime == null ? null : endOfWorkTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_detail.team_id
	 * @return  the value of t_user_detail.team_id
	 * @mbg.generated
	 */
	public Integer getTeamId() {
		return teamId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_detail.team_id
	 * @param teamId  the value for t_user_detail.team_id
	 * @mbg.generated
	 */
	public void setTeamId(Integer teamId) {
		this.teamId = teamId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_detail.delete_flag
	 * @return  the value of t_user_detail.delete_flag
	 * @mbg.generated
	 */
	public String getDeleteFlag() {
		return deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_detail.delete_flag
	 * @param deleteFlag  the value for t_user_detail.delete_flag
	 * @mbg.generated
	 */
	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
	}
}