package com.example.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TUserDetailExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	public TUserDetailExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andStartOfWorkTimeIsNull() {
			addCriterion("start_of_work_time is null");
			return (Criteria) this;
		}

		public Criteria andStartOfWorkTimeIsNotNull() {
			addCriterion("start_of_work_time is not null");
			return (Criteria) this;
		}

		public Criteria andStartOfWorkTimeEqualTo(String value) {
			addCriterion("start_of_work_time =", value, "startOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andStartOfWorkTimeNotEqualTo(String value) {
			addCriterion("start_of_work_time <>", value, "startOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andStartOfWorkTimeGreaterThan(String value) {
			addCriterion("start_of_work_time >", value, "startOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andStartOfWorkTimeGreaterThanOrEqualTo(String value) {
			addCriterion("start_of_work_time >=", value, "startOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andStartOfWorkTimeLessThan(String value) {
			addCriterion("start_of_work_time <", value, "startOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andStartOfWorkTimeLessThanOrEqualTo(String value) {
			addCriterion("start_of_work_time <=", value, "startOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andStartOfWorkTimeLike(String value) {
			addCriterion("start_of_work_time like", value, "startOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andStartOfWorkTimeNotLike(String value) {
			addCriterion("start_of_work_time not like", value, "startOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andStartOfWorkTimeIn(List<String> values) {
			addCriterion("start_of_work_time in", values, "startOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andStartOfWorkTimeNotIn(List<String> values) {
			addCriterion("start_of_work_time not in", values, "startOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andStartOfWorkTimeBetween(String value1, String value2) {
			addCriterion("start_of_work_time between", value1, value2, "startOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andStartOfWorkTimeNotBetween(String value1, String value2) {
			addCriterion("start_of_work_time not between", value1, value2, "startOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andEndOfWorkTimeIsNull() {
			addCriterion("end_of_work_time is null");
			return (Criteria) this;
		}

		public Criteria andEndOfWorkTimeIsNotNull() {
			addCriterion("end_of_work_time is not null");
			return (Criteria) this;
		}

		public Criteria andEndOfWorkTimeEqualTo(String value) {
			addCriterion("end_of_work_time =", value, "endOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andEndOfWorkTimeNotEqualTo(String value) {
			addCriterion("end_of_work_time <>", value, "endOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andEndOfWorkTimeGreaterThan(String value) {
			addCriterion("end_of_work_time >", value, "endOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andEndOfWorkTimeGreaterThanOrEqualTo(String value) {
			addCriterion("end_of_work_time >=", value, "endOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andEndOfWorkTimeLessThan(String value) {
			addCriterion("end_of_work_time <", value, "endOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andEndOfWorkTimeLessThanOrEqualTo(String value) {
			addCriterion("end_of_work_time <=", value, "endOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andEndOfWorkTimeLike(String value) {
			addCriterion("end_of_work_time like", value, "endOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andEndOfWorkTimeNotLike(String value) {
			addCriterion("end_of_work_time not like", value, "endOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andEndOfWorkTimeIn(List<String> values) {
			addCriterion("end_of_work_time in", values, "endOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andEndOfWorkTimeNotIn(List<String> values) {
			addCriterion("end_of_work_time not in", values, "endOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andEndOfWorkTimeBetween(String value1, String value2) {
			addCriterion("end_of_work_time between", value1, value2, "endOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andEndOfWorkTimeNotBetween(String value1, String value2) {
			addCriterion("end_of_work_time not between", value1, value2, "endOfWorkTime");
			return (Criteria) this;
		}

		public Criteria andTeamIdIsNull() {
			addCriterion("team_id is null");
			return (Criteria) this;
		}

		public Criteria andTeamIdIsNotNull() {
			addCriterion("team_id is not null");
			return (Criteria) this;
		}

		public Criteria andTeamIdEqualTo(Integer value) {
			addCriterion("team_id =", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdNotEqualTo(Integer value) {
			addCriterion("team_id <>", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdGreaterThan(Integer value) {
			addCriterion("team_id >", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("team_id >=", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdLessThan(Integer value) {
			addCriterion("team_id <", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdLessThanOrEqualTo(Integer value) {
			addCriterion("team_id <=", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdIn(List<Integer> values) {
			addCriterion("team_id in", values, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdNotIn(List<Integer> values) {
			addCriterion("team_id not in", values, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdBetween(Integer value1, Integer value2) {
			addCriterion("team_id between", value1, value2, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdNotBetween(Integer value1, Integer value2) {
			addCriterion("team_id not between", value1, value2, "teamId");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagIsNull() {
			addCriterion("delete_flag is null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagIsNotNull() {
			addCriterion("delete_flag is not null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagEqualTo(String value) {
			addCriterion("delete_flag =", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagNotEqualTo(String value) {
			addCriterion("delete_flag <>", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagGreaterThan(String value) {
			addCriterion("delete_flag >", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagGreaterThanOrEqualTo(String value) {
			addCriterion("delete_flag >=", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagLessThan(String value) {
			addCriterion("delete_flag <", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagLessThanOrEqualTo(String value) {
			addCriterion("delete_flag <=", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagLike(String value) {
			addCriterion("delete_flag like", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagNotLike(String value) {
			addCriterion("delete_flag not like", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagIn(List<String> values) {
			addCriterion("delete_flag in", values, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagNotIn(List<String> values) {
			addCriterion("delete_flag not in", values, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagBetween(String value1, String value2) {
			addCriterion("delete_flag between", value1, value2, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagNotBetween(String value1, String value2) {
			addCriterion("delete_flag not between", value1, value2, "deleteFlag");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_detail
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}