package com.example.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.example.model.MRole;
import com.example.model.MRoleExample;
import com.example.model.MRoleKey;

public interface MRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_role
	 * @mbg.generated
	 */
	long countByExample(MRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_role
	 * @mbg.generated
	 */
	int deleteByExample(MRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_role
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(MRoleKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_role
	 * @mbg.generated
	 */
	int insert(MRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_role
	 * @mbg.generated
	 */
	int insertSelective(MRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_role
	 * @mbg.generated
	 */
	List<MRole> selectByExample(MRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_role
	 * @mbg.generated
	 */
	MRole selectByPrimaryKey(MRoleKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_role
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") MRole record, @Param("example") MRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_role
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") MRole record, @Param("example") MRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_role
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(MRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_role
	 * @mbg.generated
	 */
	int updateByPrimaryKey(MRole record);

	/**
	 * 全ての有効なチーム情報を取得します。
	 * @return 有効なロール情報リスト
	 */
	List<MRole> selectAll();
}