package com.example.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.example.model.MUser;
import com.example.model.MUserExample;
import com.example.model.MUserKey;

public interface MUserMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_user
	 * @mbg.generated
	 */
	long countByExample(MUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_user
	 * @mbg.generated
	 */
	int deleteByExample(MUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_user
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(MUserKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_user
	 * @mbg.generated
	 */
	int insertSelective(MUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_user
	 * @mbg.generated
	 */
	List<MUser> selectByExample(MUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_user
	 * @mbg.generated
	 */
	MUser selectByPrimaryKey(MUserKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_user
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") MUser record, @Param("example") MUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_user
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") MUser record, @Param("example") MUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_user
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(MUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_user
	 * @mbg.generated
	 */
	int updateByPrimaryKey(MUser record);

    /**
     * ログインIDでユーザーマスターを検索
     * @param loginId
     * @return ユーザー情報
     */
    MUser selectByLoginId(@Param("loginId") String loginId);

    // 20191109 五十嵐　start
    /**
     * ユーザーIDでユーザーマスターを検索
     * @param userId
     * @return ユーザー情報
     */
    MUser selectByUserId(@Param("userId") int userId);

    /**
     * ユーザー情報を新規登録
     */
    int insert(MUser record);

    /**
     * ユーザー情報を更新
     */
    int updateByUserId(MUser record);
    // 20191109 五十嵐 end

}