package com.example.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.example.model.TUserDetail;
import com.example.model.TUserDetailExample;
import com.example.model.TUserDetailKey;

public interface TUserDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	long countByExample(TUserDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	int deleteByExample(TUserDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */

	int deleteByPrimaryKey(TUserDetailKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	int insert(TUserDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */

	int insertSelective(TUserDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	List<TUserDetail> selectByExample(TUserDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	TUserDetail selectByPrimaryKey(TUserDetailKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") TUserDetail record, @Param("example") TUserDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") TUserDetail record, @Param("example") TUserDetailExample example);


	// 20191109 五十嵐 start
	/**
	 * ユーザーIDでユーザー詳細情報を検索
	 * @param userId
	 * @return ユーザー詳細情報
	 */
	TUserDetail selectByUserId(@Param("userId") int userId);



    // 20191117 横澤 start
	/**
	 * ユーザー詳細情報を削除（deleteflg更新のみのため実質更新）
	 */
	int deleteUser(TUserDetail record);
    // 20191117 横澤 end

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(TUserDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_detail
	 * @mbg.generated
	 */
	int updateByPrimaryKey(TUserDetail record);

}