package com.example.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.example.model.TWorkShift;
import com.example.model.TWorkShiftExample;
import com.example.model.TWorkShiftKey;

public interface TWorkShiftMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_shift
	 * @mbg.generated
	 */
	long countByExample(TWorkShiftExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_shift
	 * @mbg.generated
	 */
	int deleteByExample(TWorkShiftExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_shift
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(TWorkShiftKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_shift
	 * @mbg.generated
	 */
	int insert(TWorkShift record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_shift
	 * @mbg.generated
	 */
	int insertSelective(TWorkShift record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_shift
	 * @mbg.generated
	 */
	List<TWorkShift> selectByExample(TWorkShiftExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_shift
	 * @mbg.generated
	 */
	TWorkShift selectByPrimaryKey(TWorkShiftKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_shift
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") TWorkShift record, @Param("example") TWorkShiftExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_shift
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") TWorkShift record, @Param("example") TWorkShiftExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_shift
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(TWorkShift record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_shift
	 * @mbg.generated
	 */
	int updateByPrimaryKey(TWorkShift record);

	int insertOrUpdate(List<TWorkShift> recordList);
}