package com.example.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.example.model.TWorkUnitHis;
import com.example.model.TWorkUnitHisExample;
import com.example.model.TWorkUnitHisKey;

public interface TWorkUnitHisMapper {

	/**
	 * 勤怠基準日(本日時点)での紐づけ記録を取得する
	 * @param userid
	 * @return 出退勤紐づけテーブルリスト
	 */
	List<TWorkUnitHis> selectByUserIdAndCurrentDate(@Param("userId") Integer userid);


	/**
	 * 出退勤紐づけテーブルより最新のレコードを取得するメソッド。
	 * @return 出退勤紐づけテーブルの最新のレコード
	 */
	TWorkUnitHis selectLatestRecord();
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_unit_his
	 * @mbg.generated
	 */
	long countByExample(TWorkUnitHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_unit_his
	 * @mbg.generated
	 */
	int deleteByExample(TWorkUnitHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_unit_his
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(TWorkUnitHisKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_unit_his
	 * @mbg.generated
	 */
	int insert(TWorkUnitHis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_unit_his
	 * @mbg.generated
	 */
	int insertSelective(TWorkUnitHis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_unit_his
	 * @mbg.generated
	 */
	List<TWorkUnitHis> selectByExample(TWorkUnitHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_unit_his
	 * @mbg.generated
	 */
	TWorkUnitHis selectByPrimaryKey(TWorkUnitHisKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_unit_his
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") TWorkUnitHis record, @Param("example") TWorkUnitHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_unit_his
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") TWorkUnitHis record, @Param("example") TWorkUnitHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_unit_his
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(TWorkUnitHis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_unit_his
	 * @mbg.generated
	 */
	int updateByPrimaryKey(TWorkUnitHis record);
}