package com.example.repository;

import com.example.model.TWorkEndHis;
import com.example.model.TWorkEndHisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TWorkEndHisMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_end_his
	 * @mbg.generated
	 */
	long countByExample(TWorkEndHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_end_his
	 * @mbg.generated
	 */
	int deleteByExample(TWorkEndHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_end_his
	 * @mbg.generated
	 */
	int insert(TWorkEndHis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_end_his
	 * @mbg.generated
	 */
	int insertSelective(TWorkEndHis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_end_his
	 * @mbg.generated
	 */
	List<TWorkEndHis> selectByExample(TWorkEndHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_end_his
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") TWorkEndHis record, @Param("example") TWorkEndHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_end_his
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") TWorkEndHis record, @Param("example") TWorkEndHisExample example);
}