package com.example.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.example.model.TWorkEndHis;
import com.example.model.TWorkEndHisExample;

public interface TWorkEndHisMapper {

	/**
	 * workUnitHisIdを元にして1件のレコードを取得するメソッドです。
	 * @param workUnitHisId
	 * @return 退勤履歴レコードリスト
	 */
	TWorkEndHis selectByWorkUnitHisId(@Param("id") Integer workUnitHisId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_end_his
	 * @mbg.generated
	 */
	long countByExample(TWorkEndHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_end_his
	 * @mbg.generated
	 */
	int deleteByExample(TWorkEndHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_end_his
	 * @mbg.generated
	 */
	int insert(TWorkEndHis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_end_his
	 * @mbg.generated
	 */
	int insertSelective(TWorkEndHis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_end_his
	 * @mbg.generated
	 */
	List<TWorkEndHis> selectByExample(TWorkEndHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_end_his
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") TWorkEndHis record, @Param("example") TWorkEndHisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_end_his
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") TWorkEndHis record, @Param("example") TWorkEndHisExample example);
}