package com.example.repository;

import com.example.model.TWorkShift;
import com.example.model.TWorkShiftExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TWorkShiftMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_shift
	 * @mbg.generated
	 */
	long countByExample(TWorkShiftExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_shift
	 * @mbg.generated
	 */
	int deleteByExample(TWorkShiftExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_shift
	 * @mbg.generated
	 */
	int insert(TWorkShift record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_shift
	 * @mbg.generated
	 */
	int insertSelective(TWorkShift record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_shift
	 * @mbg.generated
	 */
	List<TWorkShift> selectByExample(TWorkShiftExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_shift
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") TWorkShift record, @Param("example") TWorkShiftExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_work_shift
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") TWorkShift record, @Param("example") TWorkShiftExample example);
}