package com.example.repositoy;

import com.example.model.MCode;
import com.example.model.MCodeExample;
import com.example.model.MCodeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated
     */
    long countByExample(MCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated
     */
    int deleteByExample(MCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(MCodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated
     */
    int insert(MCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated
     */
    int insertSelective(MCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated
     */
    List<MCode> selectByExample(MCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated
     */
    MCode selectByPrimaryKey(MCodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MCode record, @Param("example") MCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MCode record, @Param("example") MCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MCode record);
}