package com.example.repositoy;

import com.example.model.MUser;
import com.example.model.MUserExample;
import com.example.model.MUserKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated
     */
    long countByExample(MUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated
     */
    int deleteByExample(MUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(MUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated
     */
    int insert(MUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated
     */
    int insertSelective(MUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated
     */
    List<MUser> selectByExample(MUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated
     */
    MUser selectByPrimaryKey(MUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MUser record, @Param("example") MUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MUser record, @Param("example") MUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MUser record);
}