package com.example.repositoy;

import com.example.model.TWorkStartHis;
import com.example.model.TWorkStartHisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TWorkStartHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_start_his
     *
     * @mbg.generated
     */
    long countByExample(TWorkStartHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_start_his
     *
     * @mbg.generated
     */
    int deleteByExample(TWorkStartHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_start_his
     *
     * @mbg.generated
     */
    int insert(TWorkStartHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_start_his
     *
     * @mbg.generated
     */
    int insertSelective(TWorkStartHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_start_his
     *
     * @mbg.generated
     */
    List<TWorkStartHis> selectByExample(TWorkStartHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_start_his
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TWorkStartHis record, @Param("example") TWorkStartHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_start_his
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TWorkStartHis record, @Param("example") TWorkStartHisExample example);
}