package com.example.repositoy;

import com.example.model.TWorkUnitHis;
import com.example.model.TWorkUnitHisExample;
import com.example.model.TWorkUnitHisKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TWorkUnitHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_unit_his
     *
     * @mbg.generated
     */
    long countByExample(TWorkUnitHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_unit_his
     *
     * @mbg.generated
     */
    int deleteByExample(TWorkUnitHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_unit_his
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TWorkUnitHisKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_unit_his
     *
     * @mbg.generated
     */
    int insert(TWorkUnitHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_unit_his
     *
     * @mbg.generated
     */
    int insertSelective(TWorkUnitHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_unit_his
     *
     * @mbg.generated
     */
    List<TWorkUnitHis> selectByExample(TWorkUnitHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_unit_his
     *
     * @mbg.generated
     */
    TWorkUnitHis selectByPrimaryKey(TWorkUnitHisKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_unit_his
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TWorkUnitHis record, @Param("example") TWorkUnitHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_unit_his
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TWorkUnitHis record, @Param("example") TWorkUnitHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_unit_his
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TWorkUnitHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_work_unit_his
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TWorkUnitHis record);
}