package com.example.model;

public class MCodeKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_code.code_id
	 * @mbg.generated
	 */
	private String codeId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_code.code_id
	 * @return  the value of m_code.code_id
	 * @mbg.generated
	 */
	public String getCodeId() {
		return codeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_code.code_id
	 * @param codeId  the value for m_code.code_id
	 * @mbg.generated
	 */
	public void setCodeId(String codeId) {
		this.codeId = codeId == null ? null : codeId.trim();
	}
}