package com.example.model;

public class MTeam extends MTeamKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_team.team_name
     *
     * @mbg.generated
     */
    private String teamName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_team.team_name
     *
     * @return the value of m_team.team_name
     *
     * @mbg.generated
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_team.team_name
     *
     * @param teamName the value for m_team.team_name
     *
     * @mbg.generated
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName == null ? null : teamName.trim();
    }
}