package com.example.model;

public class MUserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user.user_id
     *
     * @return the value of m_user.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user.user_id
     *
     * @param userId the value for m_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}