package com.example.model;

import java.util.Date;

public class TRequestInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_request_info.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_request_info.request_code
     *
     * @mbg.generated
     */
    private String requestCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_request_info.preferred_date
     *
     * @mbg.generated
     */
    private Date preferredDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_request_info.requested_date
     *
     * @mbg.generated
     */
    private Date requestedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_request_info.user_id
     *
     * @return the value of t_request_info.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_request_info.user_id
     *
     * @param userId the value for t_request_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_request_info.request_code
     *
     * @return the value of t_request_info.request_code
     *
     * @mbg.generated
     */
    public String getRequestCode() {
        return requestCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_request_info.request_code
     *
     * @param requestCode the value for t_request_info.request_code
     *
     * @mbg.generated
     */
    public void setRequestCode(String requestCode) {
        this.requestCode = requestCode == null ? null : requestCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_request_info.preferred_date
     *
     * @return the value of t_request_info.preferred_date
     *
     * @mbg.generated
     */
    public Date getPreferredDate() {
        return preferredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_request_info.preferred_date
     *
     * @param preferredDate the value for t_request_info.preferred_date
     *
     * @mbg.generated
     */
    public void setPreferredDate(Date preferredDate) {
        this.preferredDate = preferredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_request_info.requested_date
     *
     * @return the value of t_request_info.requested_date
     *
     * @mbg.generated
     */
    public Date getRequestedDate() {
        return requestedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_request_info.requested_date
     *
     * @param requestedDate the value for t_request_info.requested_date
     *
     * @mbg.generated
     */
    public void setRequestedDate(Date requestedDate) {
        this.requestedDate = requestedDate;
    }
}