package com.example.model;

public class TWorkUnitHisKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_work_unit_his.work_unit_his_id
	 * @mbg.generated
	 */
	private Integer workUnitHisId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_work_unit_his.work_unit_his_id
	 * @return  the value of t_work_unit_his.work_unit_his_id
	 * @mbg.generated
	 */
	public Integer getWorkUnitHisId() {
		return workUnitHisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_work_unit_his.work_unit_his_id
	 * @param workUnitHisId  the value for t_work_unit_his.work_unit_his_id
	 * @mbg.generated
	 */
	public void setWorkUnitHisId(Integer workUnitHisId) {
		this.workUnitHisId = workUnitHisId;
	}
}