package com.example.model;

import java.util.Date;

public class TWorkStartHis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_work_start_his.work_unit_his_id
     *
     * @mbg.generated
     */
    private Integer workUnitHisId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_work_start_his.start_of_work_time
     *
     * @mbg.generated
     */
    private Date startOfWorkTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_work_start_his.work_unit_his_id
     *
     * @return the value of t_work_start_his.work_unit_his_id
     *
     * @mbg.generated
     */
    public Integer getWorkUnitHisId() {
        return workUnitHisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_work_start_his.work_unit_his_id
     *
     * @param workUnitHisId the value for t_work_start_his.work_unit_his_id
     *
     * @mbg.generated
     */
    public void setWorkUnitHisId(Integer workUnitHisId) {
        this.workUnitHisId = workUnitHisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_work_start_his.start_of_work_time
     *
     * @return the value of t_work_start_his.start_of_work_time
     *
     * @mbg.generated
     */
    public Date getStartOfWorkTime() {
        return startOfWorkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_work_start_his.start_of_work_time
     *
     * @param startOfWorkTime the value for t_work_start_his.start_of_work_time
     *
     * @mbg.generated
     */
    public void setStartOfWorkTime(Date startOfWorkTime) {
        this.startOfWorkTime = startOfWorkTime;
    }
}