package com.example.repository;

import com.example.model.MTeam;
import com.example.model.MTeamExample;
import com.example.model.MTeamKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MTeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_team
     *
     * @mbg.generated
     */
    long countByExample(MTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_team
     *
     * @mbg.generated
     */
    int deleteByExample(MTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_team
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(MTeamKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_team
     *
     * @mbg.generated
     */
    int insert(MTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_team
     *
     * @mbg.generated
     */
    int insertSelective(MTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_team
     *
     * @mbg.generated
     */
    List<MTeam> selectByExample(MTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_team
     *
     * @mbg.generated
     */
    MTeam selectByPrimaryKey(MTeamKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_team
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MTeam record, @Param("example") MTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_team
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MTeam record, @Param("example") MTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_team
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_team
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MTeam record);
}