package com.example.repository;

import com.example.model.TRequestInfo;
import com.example.model.TRequestInfoExample;
import com.example.model.TRequestInfoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TRequestInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_info
     *
     * @mbg.generated
     */
    long countByExample(TRequestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_info
     *
     * @mbg.generated
     */
    int deleteByExample(TRequestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_info
     *
     * @mbg.generated
     */
    int insert(TRequestInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_info
     *
     * @mbg.generated
     */
    int insertSelective(TRequestInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_info
     *
     * @mbg.generated
     */
    List<TRequestInfoWithBLOBs> selectByExampleWithBLOBs(TRequestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_info
     *
     * @mbg.generated
     */
    List<TRequestInfo> selectByExample(TRequestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TRequestInfoWithBLOBs record, @Param("example") TRequestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_info
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TRequestInfoWithBLOBs record, @Param("example") TRequestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TRequestInfo record, @Param("example") TRequestInfoExample example);
}